database:
  restart: always
  image: postgres:9.4.4

haproxy:
  restart: always
  image: tutum/haproxy
  ports:
    - 80:80
  links:
    - web:web1
web:
  restart: always
  build: .
  expose:
    - 80
