nginx:
  image: jwilder/nginx-proxy
  ports:
    - 80:80
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro

database:
  restart: always
  image: postgres:9.4.4
  env_file: .env_dev

web:
  restart: always
  build: .
  expose:
    - 80
  environment:
    VIRTUAL_HOST: bitfondue.*
